### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by DammyShittu** [DammyShittu/Recipe-App#11]
This issue contains the [Kanban board](https://github.com/DammyShittu/Recipe-App/projects/1) that was set up according to the project requirements.

We are a team of two members;

Adedamola Shittu - @DammyShittu, and
Titus Muthomi - @Kalunge

**Comment by oloomoses** [comment]
Hi team, 

Great job on this project.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Thank you, @oloomoses 👍
